// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3nk9tdzXOqFEdz-hVhgP15M5xHoE747I',
    appId: '1:959274154653:web:879a24836ddd5f1ed13274',
    messagingSenderId: '959274154653',
    projectId: 'goal-guradian',
    authDomain: 'goal-guradian.firebaseapp.com',
    storageBucket: 'goal-guradian.appspot.com',
    measurementId: 'G-PXHTE8N0S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLOWZHCB9FYUb0PUWqQkmnI6Vc3CJPUkc',
    appId: '1:959274154653:android:7a2bbdec62f0afd9d13274',
    messagingSenderId: '959274154653',
    projectId: 'goal-guradian',
    storageBucket: 'goal-guradian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUcJVKgrAUqQ2m_DKTSUSIErW1TQCXGRI',
    appId: '1:959274154653:ios:72c781ea4b402f95d13274',
    messagingSenderId: '959274154653',
    projectId: 'goal-guradian',
    storageBucket: 'goal-guradian.appspot.com',
    iosBundleId: 'com.example.goalGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUcJVKgrAUqQ2m_DKTSUSIErW1TQCXGRI',
    appId: '1:959274154653:ios:72c781ea4b402f95d13274',
    messagingSenderId: '959274154653',
    projectId: 'goal-guradian',
    storageBucket: 'goal-guradian.appspot.com',
    iosBundleId: 'com.example.goalGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3nk9tdzXOqFEdz-hVhgP15M5xHoE747I',
    appId: '1:959274154653:web:b3fad8bb2b0904b6d13274',
    messagingSenderId: '959274154653',
    projectId: 'goal-guradian',
    authDomain: 'goal-guradian.firebaseapp.com',
    storageBucket: 'goal-guradian.appspot.com',
    measurementId: 'G-HC1B8QP6ZX',
  );
}
